# -*- coding: utf-8 -*-
"""PAI_Project_EDA_Arham_Yunus_Awan_2430-0007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdZEMUiY9h6kjgoSSTqnp-F4mIzapfdi

**Arham Yunus Awan | 2430-0007**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Set style for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

# ============================================
# 1. LOAD THE DATA
# ============================================
print("=" * 60)
print("COVID-19 STATE DATA - EXPLORATORY DATA ANALYSIS")
print("=" * 60)

# Load the CSV file (update the path to where you saved it)
df = pd.read_csv('raw_data.csv')

print(f"\n✓ Data loaded successfully!")
print(f"Dataset shape: {df.shape[0]} rows × {df.shape[1]} columns")

# ============================================
# 2. INITIAL DATA EXPLORATION
# ============================================
print("\n" + "=" * 60)
print("BASIC DATA INFORMATION")
print("=" * 60)

print("\nFirst few rows:")
print(df.head())

print("\nColumn names and types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

# ============================================
# 3. DATA CLEANING & PREPROCESSING
# ============================================
print("\n" + "=" * 60)
print("DATA CLEANING")
print("=" * 60)

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')

# Check for missing values
print("\nMissing values per column:")
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Percentage': missing_pct
})
print(missing_df[missing_df['Missing Count'] > 0].sort_values('Missing Count', ascending=False))

# Fill NaN values with 0 for numerical columns (common for COVID data)
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(0)

print(f"\n✓ Missing values handled")

# ============================================
# 4. DESCRIPTIVE STATISTICS
# ============================================
print("\n" + "=" * 60)
print("DESCRIPTIVE STATISTICS")
print("=" * 60)

# Key metrics
key_columns = ['positive', 'negative', 'death', 'totalTestResults', 'hospitalized']
available_cols = [col for col in key_columns if col in df.columns]

print("\nSummary statistics for key metrics:")
print(df[available_cols].describe())

# Total statistics
print("\n" + "-" * 60)
print("OVERALL TOTALS (All States, All Time)")
print("-" * 60)
if 'positive' in df.columns:
    print(f"Total Positive Cases: {df['positive'].sum():,.0f}")
if 'death' in df.columns:
    print(f"Total Deaths: {df['death'].sum():,.0f}")
if 'totalTestResults' in df.columns:
    print(f"Total Tests: {df['totalTestResults'].sum():,.0f}")
if 'hospitalized' in df.columns:
    print(f"Total Hospitalizations: {df['hospitalized'].sum():,.0f}")

# ============================================
# 5. STATE-WISE ANALYSIS
# ============================================
print("\n" + "=" * 60)
print("STATE-WISE ANALYSIS")
print("=" * 60)

# Top 10 states by total positive cases
if 'positive' in df.columns and 'state' in df.columns:
    state_totals = df.groupby('state')['positive'].max().sort_values(ascending=False)
    print("\nTop 10 States by Total Positive Cases:")
    print(state_totals.head(10))

# ============================================
# 6. VISUALIZATIONS
# ============================================
print("\n" + "=" * 60)
print("GENERATING VISUALIZATIONS")
print("=" * 60)

# Create a figure with multiple subplots
fig = plt.figure(figsize=(16, 12))

# Visualization 1: Time Series - National Daily Cases
if 'positive' in df.columns:
    plt.subplot(3, 2, 1)
    daily_cases = df.groupby('date')['positive'].sum()
    plt.plot(daily_cases.index, daily_cases.values, linewidth=2, color='#e74c3c')
    plt.title('Total Positive Cases Over Time (All States)', fontsize=14, fontweight='bold')
    plt.xlabel('Date')
    plt.ylabel('Cumulative Positive Cases')
    plt.xticks(rotation=45)
    plt.grid(True, alpha=0.3)

# Visualization 2: Top 10 States Bar Chart
if 'positive' in df.columns and 'state' in df.columns:
    plt.subplot(3, 2, 2)
    top_states = df.groupby('state')['positive'].max().sort_values(ascending=False).head(10)
    plt.barh(range(len(top_states)), top_states.values, color='#3498db')
    plt.yticks(range(len(top_states)), top_states.index)
    plt.xlabel('Total Positive Cases')
    plt.title('Top 10 States by Total Cases', fontsize=14, fontweight='bold')
    plt.gca().invert_yaxis()

# Visualization 3: Death Rate Distribution
if 'positive' in df.columns and 'death' in df.columns:
    plt.subplot(3, 2, 3)
    # Calculate death rate per state (latest data point)
    latest_data = df.sort_values('date').groupby('state').last()
    latest_data['death_rate'] = (latest_data['death'] / latest_data['positive'] * 100).replace([np.inf, -np.inf], np.nan)
    plt.hist(latest_data['death_rate'].dropna(), bins=30, color='#9b59b6', edgecolor='black')
    plt.xlabel('Death Rate (%)')
    plt.ylabel('Number of States')
    plt.title('Distribution of Death Rates Across States', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)

# Visualization 4: Testing vs Positive Cases Correlation
if 'totalTestResults' in df.columns and 'positive' in df.columns:
    plt.subplot(3, 2, 4)
    latest_data = df.sort_values('date').groupby('state').last()
    plt.scatter(latest_data['totalTestResults'], latest_data['positive'], alpha=0.6, s=100, color='#2ecc71')
    plt.xlabel('Total Tests')
    plt.ylabel('Positive Cases')
    plt.title('Testing vs Positive Cases (Latest Data)', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)

# Visualization 5: Daily New Cases Trend
if 'positive' in df.columns:
    plt.subplot(3, 2, 5)
    daily_national = df.groupby('date')['positive'].sum()
    daily_new = daily_national.diff().fillna(0)
    plt.plot(daily_new.index, daily_new.values, linewidth=2, color='#f39c12')
    plt.title('Daily New Cases Trend (All States)', fontsize=14, fontweight='bold')
    plt.xlabel('Date')
    plt.ylabel('New Cases per Day')
    plt.xticks(rotation=45)
    plt.grid(True, alpha=0.3)

# Visualization 6: Hospitalization Rate
if 'hospitalized' in df.columns and 'positive' in df.columns:
    plt.subplot(3, 2, 6)
    latest_data = df.sort_values('date').groupby('state').last()
    latest_data['hosp_rate'] = (latest_data['hospitalized'] / latest_data['positive'] * 100).replace([np.inf, -np.inf], np.nan)
    plt.hist(latest_data['hosp_rate'].dropna(), bins=25, color='#1abc9c', edgecolor='black')
    plt.xlabel('Hospitalization Rate (%)')
    plt.ylabel('Number of States')
    plt.title('Distribution of Hospitalization Rates', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('covid_eda_analysis.png', dpi=300, bbox_inches='tight')
print("\n✓ Visualizations saved as 'covid_eda_analysis.png'")
plt.show()

# ============================================
# 7. CORRELATION ANALYSIS
# ============================================
print("\n" + "=" * 60)
print("CORRELATION ANALYSIS")
print("=" * 60)

# Select numerical columns for correlation
corr_columns = ['positive', 'negative', 'death', 'totalTestResults', 'hospitalized']
corr_cols_available = [col for col in corr_columns if col in df.columns]

if len(corr_cols_available) > 1:
    correlation_matrix = df[corr_cols_available].corr()

    plt.figure(figsize=(10, 8))
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0,
                square=True, linewidths=1, cbar_kws={"shrink": 0.8})
    plt.title('Correlation Matrix of COVID-19 Metrics', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig('correlation_matrix.png', dpi=300, bbox_inches='tight')
    print("\n✓ Correlation matrix saved as 'correlation_matrix.png'")
    plt.show()

    print("\nCorrelation Matrix:")
    print(correlation_matrix)

# ============================================
# 8. TIME-BASED INSIGHTS
# ============================================
print("\n" + "=" * 60)
print("TIME-BASED INSIGHTS")
print("=" * 60)

# Add month and year columns
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

# Monthly aggregation
if 'positive' in df.columns:
    monthly_cases = df.groupby(['year', 'month'])['positive'].sum().reset_index()
    print("\nMonthly case progression:")
    print(monthly_cases.tail(12))

print("\n" + "=" * 60)
print("EDA COMPLETE!")
print("=" * 60)
print("\n📊 Generated Files:")
print("  - covid_eda_analysis.png (6 visualizations)")
print("  - correlation_matrix.png (correlation heatmap)")
print("=" * 60)